# Generated by Django 3.1.3 on 2020-12-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviewScore',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Nota'),
        ),
    ]
